# Generated by Django 5.2.4 on 2025-07-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='business',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='individual',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='tax',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
