# Generated by Django 5.2.4 on 2025-07-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_status_business_status_individual_status_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='status',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='status',
            name='tax',
        ),
    ]
