# Generated by Django 5.2.4 on 2025-07-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0003_remove_category_type_remove_status_individual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='business',
        ),
    ]
